services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dn
      POSTGRES_PASSWORD: nexus2026
      POSTGRES_DB: dn_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: dn
      DATABASE_PASSWORD: nexus2026
      DATABASE_NAME: dn_db
      DATABASE_PORT: 5432
      DATABASE_HOST: db

  # frontend:
  #   build:
  #     context: ./frontend
  #   command: pnpm dev
  #   volumes:
  #      - ./frontend:/app
  #      - /app/node_modules
  #      - /app/.next
  #   ports:
  #     - "3000:3000"
  frontend:
    build:
      context: ./frontend
    command:  pnpm dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
      - pnpm_store:/pnpm/store
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
  

volumes:
  frontend_node_modules:
  frontend_next:
  pnpm_store: 
  postgres_data: